name: lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    env:
      STAGE_SSV_NETWORKS: >
        [
          {
            "networkId": 560048,
            "apiVersion": "v4",
            "apiNetwork": "hoodi",
            "api": "https://api.stage.ops.ssvlabsinternal.com/api",
            "explorerUrl": "https://hoodi-explorer.stage.ssv.network",
            "insufficientBalanceUrl": "https://faucet.stage.ssv.network",
            "googleTagSecret": "87987987987",
            "tokenAddress": "0x746c33ccc28b1363c35c09badaf41b2ffa7e6d56",
            "bAppContractAddress": "0x40d959B95e7c56962D6d388d87921c03734b9C2C",
            "setterContractAddress": "0x746c33ccc28b1363c35c09badaf41b2ffa7e6d56",
            "getterContractAddress": "0x746c33ccc28b1363c35c09badaf41b2ffa7e6d56"
          }
        ]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 20.19.6

      - uses: pnpm/action-setup@v2
        with:
          version: 10.29.3

      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm typegen && pnpm lint
        env:
          SKIP_ENV_VALIDATION: true

      - name: Run test stage build
        if: github.ref == 'refs/heads/stage'
        env:
          SSV_NETWORKS: "${{ env.STAGE_SSV_NETWORKS }}"
          NEXT_PUBLIC_SSV_NETWORKS: "${{ env.STAGE_SSV_NETWORKS }}"
          SITE_URL: "https://explorer.stage.ssv.network"
          COINCECKO_API_URL: "https://api.coingecko.com/api/"

        run: pnpm build
